import type { Application, JobInfo, License, Player, Warrant } from "@/types";

export const mockPlayer: Player = {
  serverId: 12,
  citizenId: "LSPD-09F4A2",
  firstName: "Marcus",
  lastName: "Reyes",
  dob: "1994-08-12",
  phone: "555-0142",
  cash: 1245,
  bank: 18420,
  job: { id: "unemployed", name: "Unemployed", grade: "—", salary: 0 },
  idCard: {
    citizenId: "LSPD-09F4A2",
    status: "active",
    issuedAt: "2025-03-04",
    signature: "M. Reyes",
  },
};

export const mockLicenses: License[] = [
  {
    id: "lic-drive",
    type: "driving",
    name: "Driving License",
    status: "active",
    issuedAt: "2025-01-12",
    expiresAt: "2027-01-12",
    fee: 250,
    requirements: ["Valid Citizen ID", "Pass theory exam", "Pass road test"],
  },
  {
    id: "lic-moto",
    type: "motorcycle",
    name: "Motorcycle License",
    status: "none",
    fee: 200,
    requirements: ["Valid Citizen ID", "Pass motorcycle safety course"],
  },
  {
    id: "lic-gun",
    type: "gun",
    name: "Firearms License",
    status: "pending",
    fee: 750,
    requirements: ["Clean criminal record", "Background check", "Safety class"],
  },
  {
    id: "lic-boat",
    type: "boat",
    name: "Boat License",
    status: "none",
    fee: 180,
    requirements: ["Valid Citizen ID", "Pass nautical exam"],
  },
  {
    id: "lic-pilot",
    type: "pilot",
    name: "Pilot License",
    status: "expired",
    issuedAt: "2023-06-01",
    expiresAt: "2025-06-01",
    fee: 1500,
    requirements: ["Medical clearance", "Flight school certificate", "100h logged"],
  },
];

export const mockJobs: JobInfo[] = [
  {
    id: "police",
    name: "Police Officer",
    grade: "Cadet → Chief",
    salary: [1800, 6400],
    icon: "Shield",
    description: "Serve and protect Los Santos. Patrol, investigate, and respond to emergencies.",
    requirements: ["Clean record", "Pass academy", "Firearms license"],
  },
  {
    id: "ems",
    name: "EMS Paramedic",
    grade: "Trainee → Chief Surgeon",
    salary: [1600, 5800],
    icon: "HeartPulse",
    description: "Save lives. Respond to medical emergencies across the city.",
    requirements: ["Medical training", "Clean record"],
  },
  {
    id: "taxi",
    name: "Taxi Driver",
    grade: "Driver",
    salary: [900, 1800],
    icon: "Car",
    description: "Drive citizens around the city. Flexible hours.",
    requirements: ["Driving license"],
  },
  {
    id: "mechanic",
    name: "Mechanic",
    grade: "Apprentice → Master",
    salary: [1400, 4200],
    icon: "Wrench",
    description: "Repair and upgrade vehicles at certified shops.",
    requirements: ["Driving license", "Pass technical exam"],
  },
  {
    id: "delivery",
    name: "Delivery Driver",
    grade: "Courier",
    salary: [800, 1600],
    icon: "Package",
    description: "Deliver packages across Los Santos and Blaine County.",
    requirements: ["Driving license"],
  },
  {
    id: "gov",
    name: "Government Worker",
    grade: "Clerk → Director",
    salary: [1500, 4800],
    icon: "Landmark",
    description: "Process citizen applications and maintain civic operations.",
    requirements: ["Valid ID", "Background check"],
  },
];

export const mockApplications: Application[] = [
  {
    id: "app-1",
    kind: "license",
    target: "gun",
    label: "Firearms License",
    status: "pending",
    createdAt: "2026-06-10T14:22:00Z",
    notes: "Under review by LSPD background unit.",
  },
  {
    id: "app-2",
    kind: "job",
    target: "ems",
    label: "EMS Paramedic",
    status: "approved",
    createdAt: "2026-05-28T09:10:00Z",
    notes: "Welcome aboard. Report to Pillbox Medical.",
  },
  {
    id: "app-3",
    kind: "id",
    target: "id-card",
    label: "ID Card Renewal",
    status: "approved",
    createdAt: "2026-03-04T11:00:00Z",
  },
  {
    id: "app-4",
    kind: "license",
    target: "pilot",
    label: "Pilot License Renewal",
    status: "rejected",
    createdAt: "2026-05-15T16:40:00Z",
    notes: "Medical clearance expired. Resubmit after exam.",
  },
];

export const mockWarrants: Warrant[] = [
  {
    id: "w-1",
    citizenId: "LSPD-09F4A2",
    citizenName: "Marcus Reyes",
    type: "bench",
    status: "active",
    charges: "Failure to appear — traffic court",
    issuedBy: "LSPD Judicial Unit",
    issuedAt: "2026-06-08T10:00:00Z",
    expiresAt: "2026-09-08T10:00:00Z",
    notes: "Subject failed to appear for scheduled hearing on 2026-06-05.",
  },
  {
    id: "w-2",
    citizenId: "LS-7C21B8",
    citizenName: "Elena Voss",
    type: "arrest",
    status: "active",
    charges: "Armed robbery — Fleeca Bank",
    issuedBy: "Det. M. Chen, LSPD",
    issuedAt: "2026-06-11T18:30:00Z",
    notes: "Consider armed and dangerous. Do not approach alone.",
  },
  {
    id: "w-3",
    citizenId: "LS-A9043D",
    citizenName: "James Ortiz",
    type: "search",
    status: "served",
    charges: "Possession with intent — narcotics",
    issuedBy: "Judge R. Whitfield",
    issuedAt: "2026-05-20T14:00:00Z",
    notes: "Warrant executed 2026-05-22. Evidence logged.",
  },
  {
    id: "w-4",
    citizenId: "LS-3F8812",
    citizenName: "Tanya Brooks",
    type: "bench",
    status: "expired",
    charges: "Unpaid citations — aggregate",
    issuedBy: "City Clerk Office",
    issuedAt: "2025-12-01T09:00:00Z",
    expiresAt: "2026-03-01T09:00:00Z",
    notes: "Expired without service.",
  },
];
