/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarrantsRouteImport } from './routes/warrants'
import { Route as LicensesRouteImport } from './routes/licenses'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as IdCardRouteImport } from './routes/id-card'
import { Route as GovernmentInfoRouteImport } from './routes/government-info'
import { Route as DmvRouteImport } from './routes/dmv'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as IndexRouteImport } from './routes/index'

const WarrantsRoute = WarrantsRouteImport.update({
  id: '/warrants',
  path: '/warrants',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensesRoute = LicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const IdCardRoute = IdCardRouteImport.update({
  id: '/id-card',
  path: '/id-card',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentInfoRoute = GovernmentInfoRouteImport.update({
  id: '/government-info',
  path: '/government-info',
  getParentRoute: () => rootRouteImport,
} as any)
const DmvRoute = DmvRouteImport.update({
  id: '/dmv',
  path: '/dmv',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/dmv': typeof DmvRoute
  '/government-info': typeof GovernmentInfoRoute
  '/id-card': typeof IdCardRoute
  '/jobs': typeof JobsRoute
  '/licenses': typeof LicensesRoute
  '/warrants': typeof WarrantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/dmv': typeof DmvRoute
  '/government-info': typeof GovernmentInfoRoute
  '/id-card': typeof IdCardRoute
  '/jobs': typeof JobsRoute
  '/licenses': typeof LicensesRoute
  '/warrants': typeof WarrantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/dmv': typeof DmvRoute
  '/government-info': typeof GovernmentInfoRoute
  '/id-card': typeof IdCardRoute
  '/jobs': typeof JobsRoute
  '/licenses': typeof LicensesRoute
  '/warrants': typeof WarrantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/dmv'
    | '/government-info'
    | '/id-card'
    | '/jobs'
    | '/licenses'
    | '/warrants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/dmv'
    | '/government-info'
    | '/id-card'
    | '/jobs'
    | '/licenses'
    | '/warrants'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/dmv'
    | '/government-info'
    | '/id-card'
    | '/jobs'
    | '/licenses'
    | '/warrants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  DmvRoute: typeof DmvRoute
  GovernmentInfoRoute: typeof GovernmentInfoRoute
  IdCardRoute: typeof IdCardRoute
  JobsRoute: typeof JobsRoute
  LicensesRoute: typeof LicensesRoute
  WarrantsRoute: typeof WarrantsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warrants': {
      id: '/warrants'
      path: '/warrants'
      fullPath: '/warrants'
      preLoaderRoute: typeof WarrantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenses': {
      id: '/licenses'
      path: '/licenses'
      fullPath: '/licenses'
      preLoaderRoute: typeof LicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/id-card': {
      id: '/id-card'
      path: '/id-card'
      fullPath: '/id-card'
      preLoaderRoute: typeof IdCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government-info': {
      id: '/government-info'
      path: '/government-info'
      fullPath: '/government-info'
      preLoaderRoute: typeof GovernmentInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmv': {
      id: '/dmv'
      path: '/dmv'
      fullPath: '/dmv'
      preLoaderRoute: typeof DmvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  DmvRoute: DmvRoute,
  GovernmentInfoRoute: GovernmentInfoRoute,
  IdCardRoute: IdCardRoute,
  JobsRoute: JobsRoute,
  LicensesRoute: LicensesRoute,
  WarrantsRoute: WarrantsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
